"""Share identical immutable built-in font tables, without runtime work.

The checked-in fontconvert output remains the source of truth. Only interval,
kerning and ligature tables are shared; bitmaps, glyphs and compression groups
are copied unchanged. Full and OMIT_FONTS profiles are generated independently
so a slim font never pulls in a table belonging to an omitted face.
"""

import argparse
from dataclasses import dataclass
from pathlib import Path
import re


TABLE_TYPES = {
    "Intervals": ("EpdUnicodeInterval", 3, 12),
    "KernLeftCodepoints": ("uint16_t", 1, 2),
    "KernLeftClassIds": ("uint8_t", 1, 1),
    "KernRightCodepoints": ("uint16_t", 1, 2),
    "KernRightClassIds": ("uint8_t", 1, 1),
    "KernRowOffsets": ("uint16_t", 1, 2),
    "KernSparseCols": ("uint8_t", 1, 1),
    "KernSparseValues": ("int8_t", 1, 1),
    "LigaturePairs": ("EpdLigaturePair", 2, 8),
}
ARRAY_RE = re.compile(
    r"static\s+const\s+(\w+)\s+(\w+)\s*\[\s*(\d*)\s*\]\s*=\s*\{(.*?)\}\s*;",
    re.DOTALL,
)
COMMENT_RE = re.compile(r"/\*.*?\*/|//[^\n]*", re.DOTALL)
TOKEN_RE = re.compile(r"\s+|[{},]|[+-]?(?:0[xX][0-9a-fA-F]+|\d+)[uUlL]*")


@dataclass(frozen=True)
class Table:
    name: str
    ctype: str
    tokens: tuple
    count: int
    size: int
    start: int
    end: int

    @property
    def key(self):
        # No hash-only comparison: type, shape and all numeric values must match.
        return self.ctype, self.count, self.tokens


def numeric_tokens(body):
    body = COMMENT_RE.sub("", body)
    tokens = []
    position = 0
    while position < len(body):
        match = TOKEN_RE.match(body, position)
        if not match:
            raise ValueError(f"Unsupported font table initializer near {body[position:position + 32]!r}")
        token = match.group()
        position = match.end()
        if token.isspace():
            continue
        if token in ("{", "}", ","):
            tokens.append(token)
        else:
            literal = token.rstrip("uUlL")
            unsigned = literal.lstrip("+-")
            base = 16 if unsigned.lower().startswith("0x") else (8 if len(unsigned) > 1 and unsigned[0] == "0" else 10)
            tokens.append(int(literal, base))
    return tuple(tokens)


def parse_tables(source):
    tables = []
    for match in ARRAY_RE.finditer(source):
        ctype, name, declared_count, body = match.groups()
        suffix = next((suffix for suffix in TABLE_TYPES if name.endswith(suffix)), None)
        if suffix is None:
            continue
        expected_type, fields, element_size = TABLE_TYPES[suffix]
        if ctype != expected_type:
            raise ValueError(f"Unexpected type {ctype} for {name}")
        tokens = numeric_tokens(body)
        numbers = sum(isinstance(token, int) for token in tokens)
        if numbers % fields:
            raise ValueError(f"Incomplete record in {name}")
        count = numbers // fields
        if declared_count and int(declared_count) != count:
            raise ValueError(f"Declared size does not match initializer for {name}")
        tables.append(Table(name, ctype, tokens, count, count * element_size, match.start(), match.end()))
    # Fail closed if a regenerated candidate no longer follows the supported grammar.
    declarations = re.findall(r"static\s+const\s+\w+\s+(\w+)\s*\[", source)
    candidates = {name for name in declarations if any(name.endswith(suffix) for suffix in TABLE_TYPES)}
    if candidates != {table.name for table in tables}:
        raise ValueError("Unsupported or duplicate font table declaration")
    return tables


def selected_headers(all_header, slim=False):
    # Ignore the generated-header branch in all.h. The original includes remain
    # authoritative for both regular firmware and builds outside PlatformIO.
    if slim:
        all_header = re.sub(r"#ifndef OMIT_FONTS\b.*?#endif", "", all_header, flags=re.DOTALL)
    names = re.findall(r"#include\s+<builtinFonts/([\w]+\.h)>", all_header)
    if not names or len(names) != len(set(names)):
        raise ValueError("Missing or duplicate source font includes in builtinFonts/all.h")
    return names


def deduplicate(sources):
    canonical = {}
    output = ["// Generated by scripts/build_builtin_fonts.py; do not edit.\n#pragma once\n"]
    saved = 0
    shared = 0
    symbols = set()
    for filename, source in sources:
        replacements = {}
        chunks = []
        position = 0
        for table in parse_tables(source):
            if table.name in symbols:
                raise ValueError(f"Duplicate font symbol {table.name}")
            symbols.add(table.name)
            chunks.append(source[position:table.start])
            # Empty arrays have no useful savings; leave their identities alone.
            previous = canonical.get(table.key) if table.count else None
            if previous:
                replacements[table.name] = previous
                chunks.append(f"// {table.name} shares the immutable {previous} table.\n")
                saved += table.size
                shared += 1
            else:
                canonical[table.key] = table.name
                chunks.append(source[table.start:table.end])
            position = table.end
        chunks.append(source[position:])
        rewritten = "".join(chunks)
        if replacements:
            identifiers = re.compile(r"\b(?:" + "|".join(map(re.escape, replacements)) + r")\b")
            rewritten = identifiers.sub(lambda match: replacements[match.group()], rewritten)
        output.append(f"\n// Source: {filename}\n" + rewritten)
    return "".join(output), saved, shared


def write_if_changed(path, content):
    if path.is_file() and path.read_text(encoding="utf-8") == content:
        return False
    path.write_text(content, encoding="utf-8", newline="\n")
    return True


def generate(project_dir):
    fonts = Path(project_dir) / "lib" / "EpdFont" / "builtinFonts"
    all_header = (fonts / "all.h").read_text(encoding="utf-8")
    results = {}
    for profile, slim in (("full", False), ("slim", True)):
        sources = [(name, (fonts / name).read_text(encoding="utf-8")) for name in selected_headers(all_header, slim)]
        content, saved, shared = deduplicate(sources)
        changed = write_if_changed(fonts / f"{profile}.generated.h", content)
        results[profile] = {"faces": len(sources), "saved_bytes": saved, "shared_tables": shared, "changed": changed}
        print(f"Built-in fonts ({profile}): {len(sources)} faces, {shared} shared tables, {saved:,} bytes deduplicated")
    return results


if "Import" in globals():
    Import("env")  # noqa: F821 -- provided by PlatformIO
    generate(env.subst("$PROJECT_DIR"))  # noqa: F821
elif __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project-dir", type=Path, default=Path(__file__).resolve().parents[1])
    generate(parser.parse_args().project_dir)
